version: '3'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'open_web_library'
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgres/data
volumes:
  data:
    external: true
