spring:
  profiles:
    active: development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/open_web_library
    username: postgres
    password: postgres
  cloud:
    gcp:
      credentials:
        location: "file:/Users/kuratadaisuke/Projects/open-web-library/open-web-library-74319408fc6c.json"
        scopes: "DEFAULT_SCOPES,https://www.googleapis.com/auth/cloud-vision"
      project-id: "open-web-library"
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
logging:
  level:
    org.springframework: ERROR
    com.github.dkurata38.open_web_library: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
application:
  security:
    cors-permit-host: "http://localhost:8000"
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

