package com.github.dkurata38.open_web_library.repository.member_credential;

import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface MemberCredentialTableMapper {
    MemberCredentialTable selectByLoginId(String loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_credential
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String memberCredentialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_credential
     *
     * @mbg.generated
     */
    int insert(MemberCredentialTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_credential
     *
     * @mbg.generated
     */
    MemberCredentialTable selectByPrimaryKey(String memberCredentialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_credential
     *
     * @mbg.generated
     */
    List<MemberCredentialTable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_credential
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MemberCredentialTable record);
}
