package com.github.dkurata38.open_web_library.repository.member_credential;

import java.time.LocalDateTime;

public class MemberCredentialTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_credential.member_credential_id
     *
     * @mbg.generated
     */
    private String memberCredentialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_credential.member_id
     *
     * @mbg.generated
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_credential.login_id
     *
     * @mbg.generated
     */
    private String loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_credential.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_credential.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_credential.updated_at
     *
     * @mbg.generated
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_credential.member_credential_id
     *
     * @return the value of member_credential.member_credential_id
     *
     * @mbg.generated
     */
    public String getMemberCredentialId() {
        return memberCredentialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_credential.member_credential_id
     *
     * @param memberCredentialId the value for member_credential.member_credential_id
     *
     * @mbg.generated
     */
    public void setMemberCredentialId(String memberCredentialId) {
        this.memberCredentialId = memberCredentialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_credential.member_id
     *
     * @return the value of member_credential.member_id
     *
     * @mbg.generated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_credential.member_id
     *
     * @param memberId the value for member_credential.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_credential.login_id
     *
     * @return the value of member_credential.login_id
     *
     * @mbg.generated
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_credential.login_id
     *
     * @param loginId the value for member_credential.login_id
     *
     * @mbg.generated
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_credential.password
     *
     * @return the value of member_credential.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_credential.password
     *
     * @param password the value for member_credential.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_credential.created_at
     *
     * @return the value of member_credential.created_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_credential.created_at
     *
     * @param createdAt the value for member_credential.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_credential.updated_at
     *
     * @return the value of member_credential.updated_at
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_credential.updated_at
     *
     * @param updatedAt the value for member_credential.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
